chore(githooks): update to manage lua files in `fnl/`

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -13,19 +13,21 @@ root=$(git rev-parse --show-toplevel)
 fnl_dir="$root/fnl"
 lua_dir="$root/lua"
 
-declare -A lua_exceptions=(
-  ["lua/emission/config.lua"]=1
-)
+# Make sure the header is present in all the lua files under fnl/.
+lua_in_fnl_header='-- NOTE: This file will be copied into lua/ by make.'
+while read -r src_file; do
+  if ! grep -q -m 1 -F -- "$lua_in_fnl_header" "$src_file"; then
+    sed -i "1i${lua_in_fnl_header}" "$src_file"
+    echo "Inserted missing header to $src_file, and stage the entire file."
+    git add "$src_file"
+  fi
+done < <(git diff --name-only --cached HEAD~ -- "$fnl_dir/*.lua")
 
 make build >/dev/null
 
 # Unstage all the compiled lua files except deleted ones.
 while read -r lua_file; do
-  set +u
-  if [[ "${lua_exceptions[$lua_file]}" == "" ]]; then
-    git restore --staged "$lua_file" >/dev/null
-  fi
-  set -u
+  git restore --staged "$lua_file" >/dev/null
 done < <(git diff --name-only --cached --diff-filter=dr HEAD~ -- "$lua_dir")
 
 # Stage the compiled lua files corresponding to currently staged fnl files.
